version: '3.9'
services:
#  frontend:
#    build: ./frontend
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./frontend:/app
#    environment:
#      - REACT_APP_API_URL=http://localhost:8000

  api:
    ports:
      # Exposes application port.
      - "8000:8000"
    # Declare path of folder containing Dockerfile.

    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      # Adds current directory as volume.
      - ../:/code
    environment:
      # Enables autoreload.
      RELOAD: "True"
      PYTHONPATH: "/code"
